input {
  file {
    path => "/var/log/suricata/eve.json" # Chemin vers les logs Suricata
    codec => json
    start_position => "beginning"
    sincedb_path => "/dev/null" # Pour relire le fichier depuis le début au test
  }
}

filter {
  if [event_type] == "alert" {
    mutate {
      add_tag => [ "suricata_alert" ]
      # On peut ajouter ici une classification par criticité
    }
  }
  
  # Ajout de la géolocalisation si tu as l'option activée
  geoip {
    source => "src_ip"
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "suricata-%{+YYYY.MM.dd}" # Crée un index par jour
  }
  
  # Optionnel : affiche aussi les logs dans ta console pour debug
  stdout { codec => rubydebug }
}